# Generated by Django 4.1.3 on 2023-02-04 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trakergy', '0003_trip_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
