# Generated by Django 4.1.3 on 2023-02-05 16:09

from django.db import migrations, models
import trakergy.models


class Migration(migrations.Migration):

    dependencies = [
        ('trakergy', '0003_trip_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=trakergy.models.upload_to)),
            ],
        ),
    ]
