# Generated by Django 4.1.3 on 2023-02-04 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trakergy', '0004_trip_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='image_url',
            field=models.URLField(null=True),
        ),
    ]
