# Generated by Django 4.1.3 on 2023-02-04 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trakergy', '0005_trip_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='image_url',
            field=models.URLField(max_length=500, null=True),
        ),
    ]
