# Generated by Django 4.1.3 on 2023-02-06 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trakergy', '0004_mediaitem'),
        ('trakergy', '0006_alter_trip_image_url'),
    ]

    operations = [
    ]
