# Generated by Django 4.1.3 on 2023-02-06 19:18

from django.db import migrations, models
import trakergy.models


class Migration(migrations.Migration):

    dependencies = [
        ('trakergy', '0007_merge_0004_mediaitem_0006_alter_trip_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=trakergy.models.upload_to, validators=[trakergy.models.validate_image]),
        ),
    ]
