# Generated by Django 4.1.3 on 2023-02-05 23:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trakergy', '0008_alter_mediaitem_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='users_to_split',
        ),
        migrations.AlterField(
            model_name='expense',
            name='payer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_payer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_paid', models.BooleanField(default=False)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trakergy.expense')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='expense',
            name='users',
            field=models.ManyToManyField(related_name='expense_users', through='trakergy.Payment', to=settings.AUTH_USER_MODEL),
        ),
    ]
