# Generated by Django 4.1.3 on 2023-02-06 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trakergy', '0009_remove_expense_users_to_split_alter_expense_payer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='users',
            new_name='users_to_split',
        ),
    ]
