const AUTH_ACTION_TYPES = {
    ERROR: 'ERROR',
    SIGN_UP: 'SIGN_UP',
    LOG_IN: 'LOG_IN',
    LOG_OUT: 'LOG_OUT',
};

const PERSONAL_REPORTS_ACTION_TYPES = {
    GET_ALL_YEARS: 'GET_ALL_YEARS',
    SUM_BY_TYPE: 'SUM_BY_TYPE',
    SUM_BY_TYPE_LAST_X_YEARS: 'SUM_BY_TYPE_LAST_X_YEARS',
};

export { AUTH_ACTION_TYPES, PERSONAL_REPORTS_ACTION_TYPES };
